# Uncomment the next line to define a global platform for your project
platform :ios, ’10.0’

target 'Q100' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for Q100
  pod 'Google-Mobile-Ads-SDK'
  pod 'Firebase/Core'
  # pod ‘Versions’
  # pod 'ObjectMapper', '~> 2.2'
  # pod ‘SwiftyJSON’
  # pod 'AlamofireObjectMapper', '~> 4.0'
  
end
